env:
  node: true
  es2021: true

extends:
  - eslint:recommended
  - airbnb-base  # Si utilizas Airbnb como estilo de codificación

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  no-console: off
  import/extensions: off

