/* eslint-disable no-underscore-dangle */
env:
  node: true
  es2021: true

extends:
  - eslint:recommended
  - airbnb-base  # Si utilizas Airbnb como estilo de codificación

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  no-console: off
  import/extensions: off
  no-underscore-dangle:
    -error
    -allow: ["__filename", "__dirname"]

